name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t muhammadumar30/assignment-4_2 .

    - name: Login to dockerhub
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Push to dockerhub
      run: docker push muhammadumar30/assignment-4_2
